<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promesas</title>
</head>
<body>
    <h1>Promesas</h1>
    <script>
        //promesas trabajan con resolve y con reject. Se puede ver como un if / else

        //usamos la misma funcion cuadradoCallback de la clase anterior

        function cuadradoPromise(value){
            if (typeof value !== "number"){ 
                return Promise.reject(`Error: el valor ${value} ingresado no es un numero`);
            }

            return new Promise((resolve,reject)=>{
                setTimeout(() => {                              
                    resolve({
                        value:value,
                        result:value*value
                    });

                    reject();
                }, 0 | Math.random()*1000);
            });                       
        }

        //metodos para trabajar la asincornia, then y catch
        
        cuadradoPromise(0)
            .then((obj) =>{
                //console.log(obj);
                console.log(`Inicio Promise`)
                console.log(`Promise: ${obj.value}, ${obj.result}`);
                return cuadradoPromise(1)
            })
            .then (obj =>{
                console.log(`Promise: ${obj.value}, ${obj.result}`);
                return cuadradoPromise(2)
            })
            .then (obj =>{
                console.log(`Promise: ${obj.value}, ${obj.result}`);
                return cuadradoPromise(3)
            })
            .then (obj =>{
                console.log(`Promise: ${obj.value}, ${obj.result}`);
                return cuadradoPromise(4)
            })
            .then (obj =>{
                console.log(`Promise: ${obj.value}, ${obj.result}`);
                return cuadradoPromise("5")
            })
            .then (obj =>{
                console.log(`Promise: ${obj.value}, ${obj.result}`);
                console.log("Fin Promise");
            })
            .catch(err => console.error(err));

    </script>
    
</body>
</html>